name: myoro_flutter_library
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.15

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  # Latest conflicts with the Flutter's material library like [Color].
  faker: 2.1.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  sqlite3: ^2.4.7
  sqflite_common_ffi: ^2.3.4
  sqlite3_flutter_libs: ^0.5.26
  # Conflicts with Flutter's stable channel
  path: ^1.9.0
  path_provider: ^2.1.5
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  fl_chart: ^0.69.2
  shared_preferences: ^2.3.3
  intl: 0.19.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
