name: myoro_flutter_library
description: A Flutter development toolkit.
version: 2.0.5
repository: https://github.com/antonkoetzler/myoro_flutter_library
homepage: https://github.com/antonkoetzler/myoro_flutter_library
issue_tracker: https://github.com/antonkoetzler/myoro_flutter_library/issues

topics:
  - widgets
  - meta
  - ui-components

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Latest conflicts with the Flutter's material library like [Color].
  faker: 2.1.0
  sqlite3: ^2.4.7
  sqflite_common_ffi: ^2.3.4
  sqlite3_flutter_libs: ^0.5.26
  # Conflicts with Flutter's stable channel
  path: ^1.9.0
  path_provider: ^2.1.5
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  fl_chart: ^0.69.2
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  url_launcher: ^6.3.1
  myoro_flutter_annotations: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  collection: ^1.19.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-BoldItalic.ttf
