name: storyboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  myoro_flutter_library:
    path: ../
  window_manager: ^0.4.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  # Latest conflicts with the Flutter's material library like [Color].
  faker: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true