name: storyboard
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  myoro_flutter_library:
    path: ../
  myoro_flutter_annotations: ^1.4.9
    # path: ../../myoro_flutter_annotations
  window_manager: ^0.4.3
  # Latest conflicts with the Flutter's material library like [Color].
  faker: 2.1.0
  kiwi: ^5.0.1
  shared_preferences: ^2.3.5
  go_router: ^15.0.0
  collection: ^1.19.1
  provider: ^6.1.5
  icon_data_parser: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/are_you_silly.jpg
    - assets/images/happy_cat.jpg
    - assets/images/snazzy_cat.jpg
