name: Dart fix & format checks

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Get code.
      - name: Install actions checkout
        uses: actions/checkout@v3

      # Install Flutter (stable channel).
      - name: Install flutter using stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # Dart fix check.
      - name: Dart fix check (fails if fixes exists)
        run: dart fix --dry-run .

      # Dart format check.
      - name: Dart format check (fails if not formatted)
        run: dart format --line-length 160 -o none --set-exit-if-changed .
