name: Storyboard tests

on:
  push:
    branches:
      - main

jobs:
  storyboard_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install actions checkout
        uses: actions/checkout@v3

      - name: Install flutter using stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Disable flutter animations (speed up CI)
        run: flutter config --no-cli-animations

      - name: Download project dependencies
        run: |
          flutter pub get
          cd storyboard
          flutter pub get

      - name: Run tests
        run: |
          cd storyboard
          flutter test --coverage

      - name: Install LCOV for code coverage report generation
        run: sudo apt-get install lcov

      - name: Generate coverage report
        run: lcov --summary storyboard/coverage/lcov.info

      - name: Check coverage threshold (Must be >= 70%)
        run: |
          COVERAGE=$(lcov --summary storyboard/coverage/lcov.info | grep lines | awk '{print $2}' | sed 's/%//')
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Code coverage is below the required 70% threshold."
            exit 1
          fi
