name: Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install actions checkout
        uses: actions/checkout@v3

      - name: Install sqlite3-dev so tests run properly (Ubuntu doesn't preinstall this package)
        run: sudo apt-get install sqlite3-dev

      - name: Install LCOV for code coverage report generation
        run: sudo apt-get install lcov

      - name: Install flutter using stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Disable flutter animations (speed up CI)
        run: flutter config --no-cli-animations

      - name: Dart fix check (fails if fixes exists)
        run: dart fix --dry-run .

      - name: Dart format check (fails if not formatted)
        run: dart format --line-length 80 -o none --set-exit-if-changed .

      - name: Download MFL dependencies
        run: |
          flutter pub get
          cd storyboard
          flutter pub get

      - name: Run MFL tests
        run: flutter test --coverage

      - name: Generate coverage report
        run: lcov --summary coverage/lcov.info

      - name: Check coverage threshold for MFL (Must be >= 70%)
        run: |
          COVERAGE=$(lcov --summary coverage/lcov.info | grep lines | awk '{print $2}' | sed 's/%//')
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Code coverage is below the required 70% threshold."
            exit 1
          fi

      - name: Run storyboard tests
        run: |
          cd storyboard
          flutter test --coverage

      - name: Generate coverage report
        run: lcov --summary storyboard/coverage/lcov.info

      - name: Check coverage threshold (Must be >= 70%)
        run: |
          COVERAGE=$(lcov --summary storyboard/coverage/lcov.info | grep lines | awk '{print $2}' | sed 's/%//')
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Code coverage is below the required 70% threshold."
            exit 1
          fi
