name: MyoroFlutterLibrary & storyboard tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Get code.
      - name: Install actions checkout
        uses: actions/checkout@v3

      # Install Flutter (stable channel).
      - name: Install flutter using stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # Disable Flutter animations to speed up actions CLI.
      - name: Disable flutter animations (speed up CI)
        run: flutter config --no-cli-animations

      # Download project dependencies.
      - name: Update dependencies of package
        run: flutter pub get

      # Dart fix check.
      - name: Dart fix check (fails if fixes exists)
        run: dart fix --dry-run .

      # Dart format check.
      - name: Dart format check (fails if not formatted)
        run: dart format --line-length 160 -o none --set-exit-if-changed .

      # Run tests.
      - name: Run unit tests of package
        run: flutter test --coverage

      # Install LCOV for code coverage.
      - name: Run unit tests of package
        run: sudo apt-get install lcov

      # General LCOV report from --coverage flag in Flutter test.
      - name: Generate coverage report
        run: lcov --summary coverage/lcov.info

      # Assert that there is over 70% code coverage.
      - name: Check coverage threshold
        run: |
          COVERAGE=$(lcov --summary coverage/lcov.info | grep lines | awk '{print $2}' | sed 's/%//')
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Code coverage is below the required 70% threshold."
            exit 1
          fi
