name: MyoroFlutterLibrary & storyboard tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Get code.
      - name: Install actions checkout
        uses: actions/checkout@v3

      # Install Flutter (stable channel).
      - name: Install flutter using stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # Disable Flutter animations to speed up actions CLI.
      - name: Disable flutter animations (speed up CI)
        run: flutter config --no-cli-animations

      # Download project dependencies.
      - name: Update dependencies of package
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 5
          max_attempts: 1
          retry_on: error
          command: flutter pub get

      # Dart fix check.
      - name: Dart fix check (fails if fixes exists)
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 5
          max_attempts: 1
          command: dart fix --dry-run .

      # Dart format check.
      - name: Dart format check (fails if not formatted)
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 5
          max_attempts: 1
          command: dart format --line-length 160 -o none --set-exit-if-changed .

      # Cria um retry para o comando flutter test, caso ocorra algum erro
      - name: Run unit tests of package
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          retry_wait_seconds: 5
          max_attempts: 1
          retry_on: error
          command: flutter test
